### ISSUE TITLE
In case of error Cloudformation responds with: 'Response object is too long.'

### ISSUE THREAD

**Issue by jeroenkoknl** [binxio/cfn-postgresql-user-provider#2]
There is a 4k limit to the size of the response uploaded to S3.

Currently when there is a validation error in the `ResourceProperties` this will result in a larger document because the error message contains the JSON document and the actual schema.

While this a very descriptive error it will unfortunately not be picked up by CloudFormation because the document is larger than 4k. Instead it will say: 'Response object is too long'

**Comment by mvanholsteijn** [comment]
@jeroenkoknl thank you for your feedback. This problem was fixed in cfn_resource_provider base class since version 0.10.4. I upgraded the provider.  Sorry for any inconvenience caused.
