### ISSUE TITLE
undeploy success, but ENI still appear.

### ISSUE THREAD

**Issue by grulles** [binxio/cfn-postgresql-user-provider#9]
Hi,
First thank you for this custom ressource, very useful. 
Im' facing a issue. 
I can remove this stack, but not the stack which deployed a security group used by cfn-resource-provider.yaml. The ENI used by the lambda can't be detach from this SG. .
See : 
The ENI
AWS Lambda VPC ENI-binxio-cfn-postgresql-user-provider-059-2a0ef611-99a0-4a90-a1bc-5729f75b6833

resource  sg-0b8b2fcf05a0509b6 has a dependent object (Service: AmazonEC2; Status  Code: 400; Error Code: DependencyViolation; Request ID:  b4bd0dec-0300-42c1-bccc-c7ea5093ba1a)
--
Hope I'm clear.
English is not my mother ton.
Regards,
Damien

**Comment by mvanholsteijn** [comment]
Strange. It sounds like  a network interface created for the  lambda  has not (yet) been removed when you try to destroy the stack with the security group. 

Did it work a few minutes or hours later?

If not, please file a support request at AWS.

**Comment by grulles** [comment]
Hello,
After the stack failed, I had to delete the ENI manually. 
I will ask to my favorite AWS support? 
I will come back to you if there is a work around. 
Thank for your reply.
Damien.

**Comment by grulles** [comment]
Hello,
See the AWS support reply : 
There is a workaround which you could follow to resolve this issue and to move with completion of the stack deletion. You can perform delete stack call with 'retain resource' option to complete the delete operation. Once stack is deleted, you could manually delete the ENI and the security group.
Using SAM I'm not the same behaviour the stack made 40' to delete. This issue is due to remove the ENI and know by AWS. 
Thank again for your custom ressource. 
Have a nice day. 
Regards,
Damien.
